@php($locked = isset($expense) && $expense->status === \App\Enums\ReviewStatus::Validated)
@php($generated = isset($expense) && $expense->is_auto_generated)
<div class="grid gap-6 md:grid-cols-2">
    <div><label class="text-sm text-shell-muted" for="expense_category_id">Category</label><select id="expense_category_id" name="expense_category_id" class="app-select mt-2" required @disabled($generated || $locked)>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('expense_category_id',$expense?->expense_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select>@if($generated || $locked)<input type="hidden" name="expense_category_id" value="{{ $expense->expense_category_id }}">@endif</div>
    <div><label class="text-sm text-shell-muted" for="staff_id">Related Staff (optional)</label><select id="staff_id" name="staff_id" class="app-select mt-2" @disabled($generated || $locked)><option value="">General expense</option>@foreach($staffMembers as $staff)<option value="{{ $staff->id }}" @selected(old('staff_id',$expense?->staff_id)==$staff->id)>{{ trim($staff->first_name.' '.$staff->family_name) }}</option>@endforeach</select>@if(($generated || $locked) && $expense->staff_id)<input type="hidden" name="staff_id" value="{{ $expense->staff_id }}">@endif</div>
    <div><label class="text-sm text-shell-muted" for="month_date">Month</label><input id="month_date" name="month_date" type="date" value="{{ old('month_date',$expense?->month_date?->format('Y-m-d') ?? now()->startOfMonth()->format('Y-m-d')) }}" class="app-input mt-2" required @readonly($generated || $locked)></div>
    <div><label class="text-sm text-shell-muted" for="amount">Amount</label><input id="amount" name="amount" type="number" step="0.01" min="0" value="{{ old('amount',$expense?->amount) }}" class="app-input mt-2" required @readonly($locked)></div>
    <div><label class="text-sm text-shell-muted" for="status">Status</label><select id="status" name="status" class="app-select mt-2" @disabled($locked)><option value="draft" @selected(old('status',$expense?->status?->value ?? 'draft')==='draft')>Draft</option><option value="validated" @selected(old('status',$expense?->status?->value)==='validated')>Validated</option></select>@if($locked)<input type="hidden" name="status" value="validated">@endif</div>
</div>
<div><label class="text-sm text-shell-muted" for="note">Correction / expense note</label><textarea id="note" name="note" rows="4" class="app-input mt-2" @readonly($locked)>{{ old('note',$expense?->note) }}</textarea></div>
