@extends('layouts.app')
@section('title', 'Bank Reconciliation | MICS')
@section('eyebrow', 'Administrator · Finance')
@section('page-title', 'Bank Reconciliation')
@section('page-description', 'Compare expected cash movement with the actual bank balance and preserve an attributed variance explanation.')
@section('content')
<section class="grid gap-6"><div class="app-surface p-6"><form method="GET" class="flex items-end gap-3"><div><label for="month" class="text-sm text-shell-muted">Month</label><input id="month" type="month" name="month" value="{{ $month }}" class="app-input mt-2" required></div><button class="app-button-secondary">Load</button></form><dl class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="app-surface-strong p-4"><dt class="text-sm text-shell-muted">Opening</dt><dd class="mt-2 text-xl font-semibold">{{ number_format((float)$totals['opening'], 2) }}</dd></div><div class="app-surface-strong p-4"><dt class="text-sm text-shell-muted">Validated receipts</dt><dd class="mt-2 text-xl font-semibold">{{ number_format((float)$totals['receipts'], 2) }}</dd></div><div class="app-surface-strong p-4"><dt class="text-sm text-shell-muted">Validated expenses</dt><dd class="mt-2 text-xl font-semibold">{{ number_format((float)$totals['expenses'], 2) }}</dd></div><div class="app-surface-strong p-4"><dt class="text-sm text-shell-muted">Expected close</dt><dd class="mt-2 text-xl font-semibold">{{ number_format((float)$totals['expected'], 2) }}</dd></div></dl></div>
@if(!$bankMonth || $bankMonth->status === 'draft')<div class="app-surface p-6"><form method="POST" action="{{ route('admin.bank-months.store') }}" class="grid gap-5">@csrf<input type="hidden" name="month" value="{{ $month }}"><div><label for="closing_balance" class="text-sm text-shell-muted">Actual closing balance</label><input id="closing_balance" name="closing_balance" type="number" step="0.01" class="app-input mt-2" required></div><div><label for="variance_reason" class="text-sm text-shell-muted">Variance reason (required if actual differs)</label><textarea id="variance_reason" name="variance_reason" class="app-input mt-2" rows="3" minlength="10"></textarea></div><div><label for="note" class="text-sm text-shell-muted">Note</label><textarea id="note" name="note" class="app-input mt-2" rows="3"></textarea></div><button class="app-button-primary justify-self-start">Reconcile Month</button></form></div>@else<div class="app-surface p-6"><p class="font-semibold">Reconciled by {{ $bankMonth->reconciledBy?->username ?? 'deleted user' }} at {{ $bankMonth->reconciled_at?->format('d M Y H:i') }}</p><p class="mt-2 text-shell-muted">Actual close: {{ number_format((float)$bankMonth->closing_balance, 2) }}. {{ $bankMonth->variance_reason }}</p><form method="POST" action="{{ route('admin.bank-months.reopen', $bankMonth) }}" class="mt-5 grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end">@csrf<div><label for="reason" class="text-sm text-shell-muted">Reopen reason</label><textarea id="reason" name="reason" class="app-input mt-2" minlength="10" required></textarea></div><button class="app-button-danger">Reopen</button></form></div>@endif
@if($bankMonth?->events->isNotEmpty())<div class="app-surface p-6"><h3 class="font-semibold">Audit history</h3><ul class="mt-4 grid gap-3">@foreach($bankMonth->events as $event)<li class="app-surface-strong p-4 text-sm"><span class="font-semibold">{{ ucfirst($event->action) }}</span> by {{ $event->user?->username ?? 'deleted user' }} · {{ $event->occurred_at->format('d M Y H:i') }} @if($event->reason)<span class="text-shell-muted">— {{ $event->reason }}</span>@endif</li>@endforeach</ul></div>@endif</section>
@endsection
